<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ATMECSINDT-047" name="Test CH" tests="2" failures="2" timestamp="12 Jan 2015 05:06:34 GMT" time="28.605" errors="0">
  <testcase name="init" time="26.196" classname="com.jdpa.services.Entry">
    <failure type="org.openqa.selenium.StaleElementReferenceException" message="Element not found in the cache - perhaps the page has changed since it was looked up
Command duration or timeout: 1.44 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: &amp;apos;2.44.0&amp;apos;, revision: &amp;apos;76d78cf323ce037c5f92db6c1bba601c2ac43ad8&amp;apos;, time: &amp;apos;2014-10-23 13:11:40&amp;apos;
System info: host: &amp;apos;ATMECSINDT-047&amp;apos;, ip: &amp;apos;127.0.1.1&amp;apos;, os.name: &amp;apos;Linux&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;3.13.0-43-generic&amp;apos;, java.version: &amp;apos;1.7.0_72&amp;apos;
Session ID: 97de442a-42f7-4a6e-a7b5-783369f284bb
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=34.0}]">
      <![CDATA[org.openqa.selenium.StaleElementReferenceException: Element not found in the cache - perhaps the page has changed since it was looked up
Command duration or timeout: 1.44 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'ATMECSINDT-047', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-43-generic', java.version: '1.7.0_72'
Session ID: 97de442a-42f7-4a6e-a7b5-783369f284bb
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=34.0}]
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:79)
	at com.jdpa.services.Entry.init(Entry.java:62)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.StaleElementReferenceException: Element not found in the cache - perhaps the page has changed since it was looked up
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'ATMECSINDT-047', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-43-generic', java.version: '1.7.0_72'
Driver info: driver.version: unknown
	at <anonymous class>.fxdriver.cache.getElementAt(resource://fxdriver/modules/web-element-cache.js:8322:1)
	at <anonymous class>.Utils.getElementAt(file:///tmp/anonymous6362172907969270795webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:7922:10)
	at <anonymous class>.fxdriver.preconditions.visible(file:///tmp/anonymous6362172907969270795webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:8934:11)
	at <anonymous class>.DelayedCommand.prototype.checkPreconditions_(file:///tmp/anonymous6362172907969270795webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11595:15)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///tmp/anonymous6362172907969270795webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11612:11)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///tmp/anonymous6362172907969270795webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11617:7)
	at <anonymous class>.DelayedCommand.prototype.execute/<(file:///tmp/anonymous6362172907969270795webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11559:5)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- init -->
  <testcase name="firstTest" time="0.001" classname="com.jdpa.services.Entry">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.jdpa.services.DataConversion.sortJsonAsPerKey(DataConversion.java:15)
	at com.jdpa.services.Entry.firstTest(Entry.java:70)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- firstTest -->
</testsuite> <!-- Test CH -->
